imports:
    - javascript
    - php

filter:
    excluded_paths: [3rdparty/*, js/vendor/*, js/public/app.js, tests/]

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds. 10 minutes
        runs: 2         # Scrutinizer waits for the first 2 coverage submissions (unit & integration)

build:
    nodes:
      analysis:
          tests:
              override:
                  - php-scrutinizer-run
