imports:
    - javascript
    - php

filter:
    excluded_paths: [3rdparty/*, js/vendor/*, js/public/app.js]

tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds. 10 minutes
