language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
  - cd ..
  - git clone https://github.com/owncloud/core.git
  - mv music core/apps/
  - cd core
  - git submodule init
  - git submodule update
  - cd apps/music

script:
  - phpunit tests  --coverage-clover clover.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"


